spkenv/spk

- crates/spfs-cli/cmd-render/src/cmd_render.rs
- crates/spfs-cli/main/src/cmd_reset.rs
- crates/spfs-cli/main/src/cmd_run.rs
- crates/spfs/src/config.rs
- crates/spk-cli/common/src/flags.rs
Replaces the default use of the origin repo with a check that only does so if it is actually configured. This will allow for building packages locally on a machine without first setting up a configuration file.
closes #1085
> Allow building packages without an origin configured

- .github/workflows/rust.yml
- .site/spi/.spdev.yaml
- Cargo.lock
- Cargo.toml
- crates/sentry-miette/Cargo.toml
- crates/spfs/src/bootstrap.rs
- crates/spfs/src/graph/annotation.rs
- crates/spfs/src/graph/blob.rs
- crates/spfs/src/graph/entry.rs
- crates/spfs/src/graph/layer.rs
- crates/spfs/src/graph/manifest.rs
- crates/spfs/src/graph/platform.rs
- crates/spfs/src/graph/tree.rs
- crates/spfs/src/tracking/manifest.rs
- crates/spfs/src/tracking/tag.rs
- crates/spk-cli/cmd-env/src/cmd_env.rs
- crates/spk-schema/src/spec.rs
- crates/spk-storage/src/storage/spfs.rs
- cspell.json
- rpmbuild.Dockerfile
This does not bump Rust to 1.80 yet but makes changes necessary to compile and pass lints. The `std::env` related changes may need a closer look, please refer to the individual commits.
Edit: I should mention that I did not want to add the `unsafe` keyword since I didn't think it could be justified as safe.
> Changes needed for using Rust 1.80

- crates/spk-cli/common/src/flags.rs
As discussed in #1087 reuse the same logic for configuring the implicit "origin" repo as any explicitly enabled repos.
Also fix a problem from the pre-#1087 code where any explicitly enabled "origin" (with custom pin) would be replaced by the implicit one.
> Fix default origin repo not respecting --when

- crates/spk-cli/common/src/flags.rs
- crates/spk-config/src/config.rs
- crates/spk-solve/src/io.rs
This adds solver configuration and options to set the default solver and default solver to display solver output from. This will let sites configure the solver/s they want, and let individual commands override that when required.
These changes add:
- `--solver-to-show <SOLVER>` argument to commands with Solver cli flags
- `solver_to_run` to the Solver section of the spk config file
- `solver_to_show` to the Solver section of the spk config file
- environment variable defaults to `--solver-to-run` and `--solver-to-show`. They use `SPK_SOLVER__SOLVER_TO_RUN` and `SPK_SOLVER__SOLVER_TO_SHOW` respectively to line up with the spk config file
- constants for the names used on the command line for the various solvers
Examples:
```
spk explain python --solver-to-run all --solver-to-show cli
spk …
```
> Add solver config to control default the solver and displayed output

- crates/spk-solve/crates/graph/src/error.rs
- crates/spk-solve/crates/graph/src/graph.rs
- crates/spk-solve/crates/validation/src/error.rs
- crates/spk-solve/src/solver_test.rs
This tries to make the current 'Failed to resolve' solver result message a bit clearer for users. 
spk outputs this when it can't find a solution after trying everything it can:
```
ERROR spk: (link)
x Failed to resolve
```
This is a fairly rare "error". But recently people have been seeing this message and haven't understood what it means or what they can do to fix it. This doesn't address what they can do to fix it, It just tries to make the message clearer.
It changes the output to:
```
ERROR (link)
x Failed to resolve: there is no solution for these requests using the available packages
```
> Make 'Failed to resolve' solver result message clearer

- Cargo.lock
- Cargo.toml
- crates/spfs/src/config.rs
- crates/spfs/src/runtime/storage.rs
- crates/spfs/src/tracking/tag.rs
https://github.com/spkenv/spk/security/dependabot/7
Err on the safe side and generate a unique hostname if it can't be determined (on the spfs side) so runtime pruning doesn't think two runtimes from different hosts that couldn't determine the hostname are from the same host.
> Update whoami to address vulerability

- crates/spk-solve/src/io.rs
This adds a very basic interactive menu for inspecting current state the solver has reached, when using `--step/stop-on-block` or `--step-on-decision`. 
It adds methods for showing the current state's resolved packages, unresolved requests, variable requests, options, and showing all of the those when stepping or stopping. I imagine more could be added later, e.g. we have a request to launch an environment of the currently resolved packages. I have a plan to add showing graphs of the current dependencies to this menu (PR: TBD).
The menu doesn't use any other crates and appears among the normal solver output, but doesn't use the output setting the solver has. This was partly for initial implementation ease, partly to keep the existing output intact, and partly because its interactive. …
> Adds basic iteractive menu for inspecting current state of solver when stepping

- Cargo.lock
- crates/spk-cli/common/src/flags.rs
- crates/spk-solve/Cargo.toml
- crates/spk-solve/src/error.rs
- crates/spk-solve/src/io.rs
- crates/spk-solve/src/lib.rs
- cspell.json
Adds `--output-to-dir <path>` flag for logging each solver's output to a separate file for each solver run, and the ` SPK_OUTPUT_TO_DIR` env avr. The output files will be put in the given path.
It extends the `OutputKind` enum to have entries that output to a file, or `println!` and a file, or `tracing!` and a file. The interface allows for anything with the `Write` trait (and some thread-safe/task required traits). The `Copy` trait was removed from the enum in favour of cloning while wrangling the tasks, threads, mutability, and task communication messages. Let me know if there's a better way to do this.
A method was added to the enum to allow the initial output kind, i.e. `Println` or `Tracing`, to be combined with an output to file enum entry. This is used to make things appear in the …
> Add `--output-to-dir <path>` for solvers' output

- Cargo.lock
- crates/spk-config/src/config.rs
- crates/spk-schema/Cargo.toml
- crates/spk-schema/src/build_spec.rs
- crates/spk-schema/src/option.rs
- crates/spk-schema/src/v0/spec.rs
- docs/admin/config.md
At SPI we recently started building package for Rocky while on Rocky 9.3, and on Rocky the host options detect the version as `"9.3"`, whereas on CentOS the version was detected as just `"7"`. Now we are starting to build systems with Rocky 9.4, and since that generates a host option of `"rocky": "9.4"` the solver is unwilling to pick up any packages that were built on Rocky 9.3.
This PR explores one idea for solving this problem. It introduces the ability to set a `compat` value on a var option, as in:
```yaml
build:
options:
- var: distro
- var: rocky
compat: "x.b"
```
~~Note these vars would normally be auto-generated for a recipe and in this PR it auto-generates the "rocky" var with the compat enabled based on a hard coded list of distro names.~~
The logic for handling this is when …
> Distro compat range

- packages/gnu/gcc/gcc48.spk.yaml
- packages/gnu/gcc/gcc63.spk.yaml
- packages/gnu/gcc/gcc93.spk.yaml
- packages/gnu/gmp.spk.yaml
This PR is meant to update the deprecated `validation` attribut `disable` for the following pckages
- packages/gnu/gmp.spk.yaml
- packages/gnu/gcc/gcc63.spk.yaml
- packages/gnu/gcc/gcc93.spk.yaml
and add `allow` `RecursiveBuild` validation for packages/gnu/gcc/gcc63.spk.yaml
> update validation rules for gmp, gcc63 and gcc63

- Cargo.lock
- crates/spk-build/src/archive_test.rs
- crates/spk-cli/group3/Cargo.toml
- crates/spk-cli/group3/src/cmd_export.rs
- crates/spk-cli/group3/src/cmd_export_test.rs
- crates/spk-cli/group3/src/cmd_import_test.rs
- crates/spk-storage/Cargo.toml
- crates/spk-storage/src/lib.rs
- crates/spk-storage/src/storage/archive.rs
- crates/spk-storage/src/storage/mod.rs
- crates/spk-storage/src/storage/spfs.rs
In particular, `spk export --local-repo-only ...` would export packages from the origin repo.
This necessitated adding another level of "handle" indirection to deal with the different type flavors of SpfsRepository.
> Fix `spk export` not respecting repository arguments

- Cargo.lock
- Cargo.toml
- crates/spk-solve/Cargo.toml
https://github.com/spkenv/spk/security/dependabot/5
Update the versions of crossterm and tokio so we no longer depend on the vulnerable version of mio.
> Update mio to address vulnerability

- Cargo.lock
https://github.com/spkenv/spk/security/dependabot/4
This transitive dependency comes via winfsp-sys but we're already on the latest version of that.
> cargo update shlex to address vulnerability

- crates/spk-schema/crates/foundation/src/version/compat.rs
- crates/spk-solve/src/solver.rs
- crates/spk-solve/src/solver_test.rs
The solver was panicking with "state not found" in the case where it encounters a package that embeds some other package, but that other package has already been embedded by some third package. It wanted to "eject" the real package (again) but no "real" package was in the solution at that point.
Now it checks that the package it wants to "eject" is a not an embedded package. This situation was given its own `IncompatibleReason` so the solver output will detail the packages involved.
> Handle when multiple packages embed the same package

- crates/spfs/src/config.rs
This adds the repo's name to the 'opening repository ... ' debug messages to make each mesasge clearer. It can be tricky to work out which repo each message refers to when you have complicated multi-repo configurations.
> Add repo name to 'opening repository' debug messages

- crates/spfs-cli/cmd-fuse/src/cmd_fuse.rs
- crates/spfs-cli/cmd-monitor/src/cmd_monitor.rs
- crates/spfs-cli/common/src/args.rs
- crates/spfs-vfs/src/fuse.rs
- crates/spfs/src/config.rs
- crates/spfs/src/monitor.rs
- crates/spfs/src/runtime/storage.rs
- cspell.json
- docs/admin/config.md
As mentioned in #895, there are cases where spfs-fuse never shuts down. An easy way to repro this is to `kill -9` the spfs-monitor process, so it doesn't get a chance to clean up the runtime normally.
We observe spfs-fuse processes accumulating over time on our CI runners. It could be from users canceling pipelines (maybe the runner does a `kill -9` of all the child processes?). It is also extremely common for zombie runtimes to accumulate over time (not just on CI runners), perhaps spfs-monitor is crashing / failing to cleanup commonly?
~~This is a proof of concept and enabling this or tuning the timing of the heartbeat and timeout should be a configurable thing but these are hard coded for now.~~ Configuration added!
> Add a heartbeat between spfs-monitor and spfs-fuse

- crates/spfs-vfs/src/winfsp/mount.rs
- crates/spfs/src/tracking/diff.rs
- crates/spfs/src/tracking/manifest.rs
- crates/spk-cli/cmd-build/src/cmd_build_test/mod.rs
Use a custom method for trimming '/' or "./" that doesn't change ".foo"
into "foo".
Fixes https://github.com/spkenv/spk/issues/1036
> Remove trim_start_matches targeting '.'

- crates/spk-launcher/src/main.rs
This PR add support Windows support for spk-launcher
- add symlink support using Windows lib
- spawn a process using `std::process::Command` under Windows
> add win support for spk-launcher

- crates/spk-schema/crates/foundation/src/ident_ops/parsing/mod.rs
- crates/spk-schema/crates/foundation/src/version/version_test.rs
- crates/spk-schema/crates/ident/src/lib.rs
- crates/spk-schema/crates/ident/src/parsing/mod.rs
- crates/spk-schema/crates/ident/src/parsing/parsing_test.rs
- crates/spk-schema/crates/ident/src/parsing/request.rs
- crates/spk-schema/crates/ident/src/range_ident.rs
- crates/spk-schema/crates/ident/src/range_ident_test.rs
This adds an api function for parsing a comma-separated list (csl) of range idents (packages or requests). It required an update to the parser for `package_name_not_version`, and it includes some intial proptests for parsing valid and invalid range ident comma-separated lists.
The background is that SPI had a csl parser for package requests in another tool that uses `spk` as a library. `spk` parsed the package identifiers, and the tool dealt with the list. We hit issue parsing these csl's when some of the requests contained post-releases or multiple version ranges, e.g. `pkgA/1,mypkg/2.3.1+r4,pkgB` or `mypkg/1.2.3,1.3.5,pkgC`. 
This led to the `package_name_not_version` parser. We found it wasn't parsing the packages correctly in these situations and could mistake package names for repo …
> Adds support for parsing a comma-separated list of range idents

- Cargo.lock
- Cargo.toml
- crates/is_default_derive_macro/Cargo.toml
- crates/is_default_derive_macro/src/lib.rs
- crates/spk-cli/cmd-build/src/cmd_build_test/mod.rs
- crates/spk-schema/Cargo.toml
- crates/spk-schema/crates/foundation/src/is_default.rs
- crates/spk-schema/crates/foundation/src/lib.rs
- crates/spk-schema/crates/foundation/src/version/compat.rs
- crates/spk-schema/crates/ident/src/request.rs
- crates/spk-schema/src/build_spec.rs
- crates/spk-schema/src/build_spec_test.rs
- crates/spk-schema/src/component_spec_list.rs
- crates/spk-schema/src/embedded_packages_list.rs
- crates/spk-schema/src/environ.rs
- crates/spk-schema/src/install_spec.rs
- crates/spk-schema/src/lib.rs
- crates/spk-schema/src/metadata/meta.rs
- crates/spk-schema/src/option.rs
- crates/spk-schema/src/package.rs
- crates/spk-schema/src/recipe.rs
- crates/spk-schema/src/requirements_list.rs
- crates/spk-schema/src/spec.rs
- crates/spk-schema/src/v0/platform.rs
- crates/spk-schema/src/v0/spec.rs
- crates/spk-schema/src/validation.rs
Refactor various is_default() methods into IsDefault trait
Fixes #1081. The bug causing #1081 was in `InstallSpec::is_default` as the
logic was not updated when the `environment` field was added to the struct
way back at https://github.com/spkenv/spk/blob/f4899ce1e4ac0634ee95608e322a86a358096d4d/src/api/install_spec.rs#L31
As a guard against this kind of bug in the future, an `IsDefault` trait was
created and a derive macro created to derive the `is_default` method
semi-automatically. All existing `is_default` methods have been changed to
use the trait instead.
And...
[Refactor Package::runtime_environment](https://github.com/spkenv/spk/pull/1129/commits/523943e60f764d76bff1e5e0697f94e90f64f4e6)
Both recipes and packages have the `install.environment` property, so
refactor …
> Preserve install environment

- crates/spfs-cli/main/src/cmd_edit.rs
This adds the `--allow-already-editable` flag to `spfs edit`. The flag stops `spfs edit` from exiting with an error code when the runtime environment it was run in is already editable. The allows scripts and other tools to use `spfs edit` without needing to handle the already edityable case as an error. 
Example,:
```
> spfs edit
> spfs edit
Error: (link)
× Runtime is already editable
> echo $?
1
> spfs edit --allow-already-editable
> echo $?
0
```
> Add `--allow-already-editable` flag to `spfs edit`

- Cargo.lock
- Cargo.toml
- crates/spk-schema/crates/foundation/src/version/compat/mod.rs
- crates/spk-schema/crates/foundation/src/version/compat/problems.rs
Update the version of strum to the latest version, the older version didn't support enum variants with unnamed fields. This was hiding a number of places that had been changed from named to unnamed fields without updating the format string.
> Fix IncompatibleReason Display issues

- crates/spk-schema/src/v0/spec.rs
- crates/spk-schema/src/v0/test_spec.rs
Any package requirements on an spk recipe test need to have their
requester filled in.
-RESOLVE python-pytest/7.4.3/UNZ5Q23T  (requested by )
+RESOLVE python-pytest/7.4.3/UNZ5Q23T  (requested by some-package-name/1.2.1 install test)
> Fix empty Request requester in test requirements

- crates/spk-cli/group4/src/cmd_view.rs
- crates/spk-schema/src/test.rs
An alternate to `spk info --variant` that also includes the counts of tests that would be run in each variant. This can be used by automation to detect if a CI job needs to be generated to run tests.
Resolves #1120.
Example for our python recipe that has two install tests defined:
```json
{"0":{"options":{"abi":"cp39","centos-sqlite":"3.7.17","debug":"off","gcc":"6.3"},"additional_requirements":[{"pkg":"centos-sqlite/3.7.17"}],"tests":{"sources":0,"build":0,"install":2}},"1":{"options":{"abi":"cp39","debug":"off","gcc":"6.3","sqlite":"3.9.0"},"additional_requirements":[],"tests":{"sources":0,"build":0,"install":2}},"2":{"options":{"abi":"cp39","centos-sqlite":"3.7.17","debug":"off","gcc":"9.3"},"additional_requirements":[{"pkg":"centos-sqlite/3.7.17"}],"tests":{"sources":0,"build":0,"insta …
```
> Add `spk info --variants-with-tests`

- .taplo.toml
For formatting Cargo.toml according to our prevailing standards (for those using it in their IDEs).
> Add taplo configuration file

- crates/spk-cli/group1/src/cmd_bake.rs
- crates/spk-cli/group1/src/cmd_bake_test.rs
- crates/spk-solve/crates/graph/src/graph.rs
- crates/spk-solve/src/io.rs
- crates/spk-solve/src/solver.rs
- cspell.json
This fixes a bug in `get_unresolved_requests()` where it would use `unwrap` instead of checking the result. This caused spk to panic when given requests like `mypkg/==1.0.99 mypkg/=1.0.33+r.1`.
The fix removes the `unwrap`, and changes the method to return Result for better error handling. The method needed to be reworked a bit because of the caching mechanism used to avoid recalculating unresolved requests.
> Bugfix: `get_unresolved_requests()` and incompatible requests

- .clippy.toml
- Cargo.lock
- crates/spk-schema/Cargo.toml
- crates/spk-schema/crates/foundation/src/ident_ops/parsing/mod.rs
- crates/spk-schema/crates/foundation/src/ident_ops/parsing/request.rs
- crates/spk-schema/crates/foundation/src/version/compat/problems.rs
- crates/spk-schema/crates/ident/src/ident_optversion.rs
- crates/spk-schema/crates/ident/src/ident_version.rs
- crates/spk-schema/crates/ident/src/lib.rs
- crates/spk-schema/crates/ident/src/parsing/ident.rs
- crates/spk-schema/crates/ident/src/parsing/mod.rs
- crates/spk-schema/src/component_embedded_packages.rs
- crates/spk-schema/src/component_spec.rs
- crates/spk-schema/src/embedded_components_list.rs
- crates/spk-schema/src/embedded_packages_list.rs
- crates/spk-schema/src/install_spec.rs
- crates/spk-schema/src/install_spec_test.rs
- crates/spk-schema/src/lib.rs
- crates/spk-schema/src/v0/spec.rs
- crates/spk-solve/crates/graph/src/graph.rs
- crates/spk-solve/crates/solution/src/solution.rs
- crates/spk-solve/crates/validation/src/validators/components.rs
- crates/spk-solve/crates/validation/src/validators/embedded_package.rs
- crates/spk-solve/crates/validation/src/validators/pkg_request.rs
- crates/spk-solve/crates/validation/src/validators/pkg_requirements.rs
- crates/spk-solve/src/solver.rs
- crates/spk-solve/src/solver_test.rs
- cspell.json
- docs/ref/spec.md
Addresses the question from #742.
The original spec schema had multiple places where an embedded package could be defined:
```yaml
pkg: demo/1.0.0
install:
components:
- name: comp1
embedded:
- pkg: embedded/2.0.0
embedded:
- pkg: embedded/2.0.0
```
It becomes confusing if the embedded package also has components. Where do those components get defined? How can the parent package say which of its components contains the embedded packages' components?
The package boost contains a lot of headers only needed during build so it benefits from having those files live only in the "build" component. A second package, boost-python, is also a full build of boost (plus extra python things), so it needs to embed boost. Since the boost-python package is a full build of boost, it also benefits from …
> Rework how packages describe how they contain the components of an embedded package

- crates/spfs-cli/common/src/args.rs
- cspell.json
This updates the `SPFS_LOG_TIMESTAMP` and its command line flag's value parsing to allow a more user-friendly range of number and text values for true, e.g. `1`, `true`, `True` etc..
> Updates SPFS_LOG_TIMESTAMP value parsing to allow 1 and true

- crates/spk-cli/cmd-env/src/cmd_env.rs
- crates/spk-cli/cmd-explain/src/cmd_explain.rs
- crates/spk-cli/cmd-install/src/cmd_install.rs
- crates/spk-cli/cmd-make-binary/src/cmd_make_binary.rs
- crates/spk-cli/cmd-make-recipe/src/cmd_make_recipe.rs
- crates/spk-cli/cmd-make-source/src/cmd_make_source.rs
- crates/spk-cli/cmd-render/src/cmd_render.rs
- crates/spk-cli/cmd-test/src/cmd_test.rs
- crates/spk-cli/common/src/flags.rs
- crates/spk-cli/common/src/flags_test.rs
- crates/spk-cli/group1/src/cmd_bake.rs
- crates/spk-cli/group2/src/cmd_num_variants.rs
- crates/spk-cli/group4/src/cmd_view.rs
- crates/spk-schema/src/error_test.rs
- crates/spk-schema/src/lib.rs
- crates/spk-schema/src/spec.rs
- crates/spk-schema/src/spec_test.rs
- crates/spk-schema/src/template.rs
- crates/spk-schema/src/v0/mod.rs
- crates/spk-schema/src/v0/requirements.rs
- crates/spk-schema/src/v0/spec.rs
- crates/spk-schema/src/v0/spec_test.rs
- cspell.json
This adds support to spk commands (`bake`, `env`, and `explain`) to let them take files of package requests with  a <yaml filepath>` request on their command lines.
The aim is to allow a larger number of package requests to be passed to spk command than would normally fit on a single command line. We're seeing examples of tools calling `spk bake` or `spk explain` with 350+ detailed package requests, e.g. `python/3.10.8+r3/ABCDEF` or `my-long-tool-name:{run,build,with-some-feature}/==1.2.3.4+r1`, not just `python` or `mypkg`. Some of them are starting to hit command line limits and/or are becoming unwieldy to edit.
Each file must a `yaml` formatted list of package or var requests.
Example file (can have whatever is valid for a package request, json blob, '@' specifier, etc.):
```yaml
- …
```
> Adds support to spk commands for requests files

- crates/spfs/src/bootstrap.rs
- crates/spfs/src/runtime/storage.rs
- crates/spfs/src/storage/address.rs
- crates/spfs/src/storage/fallback/repository.rs
- crates/spfs/src/storage/fs/repository.rs
- crates/spfs/src/storage/handle.rs
- crates/spfs/src/storage/mod.rs
- crates/spfs/src/storage/pinned/repository.rs
- crates/spfs/src/storage/prelude.rs
- crates/spfs/src/storage/proxy/repository.rs
- crates/spfs/src/storage/repository.rs
- crates/spfs/src/storage/rpc/repository.rs
- crates/spfs/src/storage/tar/repository.rs
- crates/spk-storage/src/storage/spfs.rs
This makes it possible for other things to have a trait bound on `Address` instead of all of `Repository`, which means other types can implement `Address` without having to also implement all of `Repository` (not shown in this commit).
Also change the method signature to return `Cow` since there are cases where an existing `Url` value can be borrowed.
> Move Repository::address to dedicated trait

- crates/spfs/src/storage/blob.rs
- crates/spfs/src/storage/fallback/repository.rs
- crates/spfs/src/storage/fs/repository.rs
- crates/spfs/src/storage/handle.rs
- crates/spfs/src/storage/layer.rs
- crates/spfs/src/storage/manifest.rs
- crates/spfs/src/storage/pinned/repository.rs
- crates/spfs/src/storage/platform.rs
- crates/spfs/src/storage/proxy/repository.rs
- crates/spfs/src/storage/repository.rs
- crates/spfs/src/storage/rpc/database.rs
- crates/spfs/src/storage/rpc/repository.rs
- crates/spfs/src/storage/tar/repository.rs
Some of these traits are fully defined and can have blanket implementations that reduce the amount of boilerplate needed.
> Add blanket implementations for Repository traits

- Cargo.toml
`nyip@imageworks` will not be in use anymore so updated with personal email
> Update author with new email address

- crates/spfs/src/graph/object.rs
Updates the `Display` impl for objects, eg:
```txt
Object(Blob, Digest { bytes: [202, 141, 243, 191, 56, 20, 155, 154, 187, 135, 144, 151, 143, 37, 122, 171, 120, 127, 60, 144, 34, 81, 167, 166, 215, 191, 51, 95, 7, 86, 80, 82] })
```
```txt
Blob[ZKG7HPZYCSNZVO4HSCLY6JL2VN4H6PEQEJI2PJWXX4ZV6B2WKBJA====]
```
> Use better display output for flatbuffer objects

- packages/spk-convert-pip/requirements.txt
This fixes a bug preventing newer packages from being converted by `spk-convert-pip` built with python 3.9, by updating the `pkginfo` version to `1.12.0`. Older python 3.7 based builds are kept at `pkginfo` `1.10.0`.
> Bugfix for newer python package conversions failing with no package names

- crates/spk-cli/group2/src/cmd_ls_test.rs
- crates/spk-schema/crates/foundation/src/option_map/filters.rs
- crates/spk-schema/src/v0/spec.rs
- cspell.json
This changes `spk ls` and `spk search` filter matching to make use of host var compatibility rules, if any are configured.
Prior to this a command line like `spk ls --host katana/7.0.4` would only match builds that had the exact values of the host options from the host it was run on, e.g.
- `arch=x86_64`
- `distro=someosname`
- `os=linux`
- `someosname=9.4`  - if there was a build with `someosname=9.3`, that build would not match.
The matching would not take into account any host var options compatibility rules that were configured. For example, the rule below should allow the value of `someosname` to be 9.4 or 9.3,or 9.2 etc.:
```
[host_options.distro_rules.someosname]
compat_rule = "x.ab"
```
These changes incoporate host compat rules into the filter matching and remove the old matching
> Change spk ls/search filters to use host var compatibility rules

- crates/spfs/src/clean.rs
- crates/spfs/src/clean_test.rs
This adds a `prune_tag_stream()` method to spfs Cleaner's api, and refactors `prune_tag_stream_and_walk()` method into `prune_tag_stream()` and `walk_attached_objects()` (to reduce some repeated code).
`prune_tag_stream()` allows a Cleaner object to be used to only prune tags from a repo, e.g. remove all tags more than 2 weeks old from a local repo on a workstation or renderfarm machine.
> Add `prune_tag_stream()` method to spfs Cleaner

- cspell.json
- packages/spk-convert-pip/spk-convert-pip
- packages/spk-convert-pip/spk-convert-pip.spk.yaml
To avoid re-converting or aggressively increasing the minimum version required for python dependencies, use `spk explain` to detect when a dependency is already satisifed by an existing package in the repo. This new behavior can be disabled with the new `--force-deps` flag.
> Skip existing packages in spk-convert-pip

- crates/spfs/Cargo.toml
- crates/spfs/src/env.rs
The new "lowerdir+" option can be used to specify multiple layers when mounting. This avoids a limitation with the "lowerdir" option which is limited to a max of 256 characters.
Use the older options when the "legacy-mount-options" feature is enabled.
Fixes: #968
> env: fix handling of long lowerdir paths in newer kernel/mount versions

- crates/spfs-cli/cmd-clean/src/cmd_clean.rs
- crates/spfs/src/clean.rs
This adds a `--prune-repeated-keep <number>` option to `spfs clean`. It allows the user to decide how many repeated tags in a tag stream to keep. The existing `--prune-repeated` option is equivalent to `--prune-repeated-keep 1`. But either option can be used. 
We have a case where we'd like to keep some repeated tags, say the last 20 , and prune the rest periodically from the local repo.
> Add `--prune-repeated-keep <number>` option to `spfs clean` 

- crates/spk-cli/common/src/flags.rs
- crates/spk-cli/common/src/flags_test.rs
This fixes a bug where the host options were being left out of the solver's initial requests. A few lines of code hand been mistakenly removed in an earlier change. This restores them and adds a test for this situation.
> Bugfix: host options were being left out of the solver's initial requests

- crates/spfs/src/resolve.rs
When `skip_runtime_save` was added, when true it unintentionally did not update the `flattened_layers` field of the runtime. This then made flattened layers subject to premature deletion by spfs-clean. Deleting in-use renders can cause existing runtimes to be left with an empty /spfs directory.
> Fix runtime flattened_layers getting lost

- Cargo.toml
This updates the `ring` dependency to `0.7.14` to avoid a bug in `0.7.13` that impacts centos 7 compiles.
> Updated ring dependency to 0.7.14 to avoid a bug in 0.7.13

- Cargo.lock
- crates/spk-build/src/build/sources_test.rs
- crates/spk-schema/src/source_spec_test.rs
If using a different vcs tool besides git to check out the spk project, these tests would fail, as they assume the working copy is a git clone.
Modify the tests to create a new git clone in a temporary directory so they don't depend on the working copy being a git clone.
> Make git source tests not require a git clone

- Cargo.lock
- crates/spk-cli/common/src/flags.rs
- crates/spk-cli/group4/Cargo.toml
- crates/spk-cli/group4/src/cmd_view.rs
- crates/spk-cli/group4/src/cmd_view_test.rs
- crates/spk-workspace/Cargo.toml
- crates/spk-workspace/src/workspace.rs
At least for the simple case where no workspace file is present, fix `find_package_template_by_file` so it compares with canonicalized path names.
Change `Workspace::load_or_default` so that if the `--workspace` argument is a directory (that doesn't contain a workspace.spk.yaml file) it still roots the virtual workspace to the given directory. This allows for workspace tests to load a virtual workspace in a temporary directory.
Add a very basic cmd_view test that verifies it is possible to use `spk view --variants filename.spk.yaml`, something which is required by the CI automation at SPI.
> Solve `spk info filename.spk.yaml` failing with file not found

- Cargo.lock
- crates/spk-cli/cmd-make-recipe/src/cmd_make_recipe.rs
- crates/spk-cli/common/src/flags.rs
- crates/spk-cli/group4/src/cmd_view.rs
- crates/spk-cli/group4/src/cmd_view_test.rs
- crates/spk-schema/src/spec.rs
- crates/spk-workspace/src/lib.rs
- crates/spk-workspace/src/workspace.rs
- crates/spk-workspace/src/workspace_test.rs
- docs/ref/spec.md
The new workspace feature has introduced a variety of regressions for
using `spk info --variants <filename>` and will error with a file not
found error for files that do actually exist.
One problem is that when a workspace spec doesn't exist, then the only
possible files that can be inspected have to exist in the root of the
virtual workspace generated, ignoring that the command line contains the
name of a valid file.
Another problem is when the workspace does exist, then the only possible
files that can be inspected have to be defined in the workspace, even
when the command line contains the name of a valid file.
Perhaps the design can be reconsidered to not use a "virtual workspace"
in these cases or at least have a fallback that tries to open the file
directly.
> Fix workspace issues stemming from new virtual workspace no accounting for path arguments

- crates/spk-cli/common/src/flags.rs
- crates/spk-cli/group4/src/cmd_view.rs
- crates/spk-cli/group4/src/cmd_view_test.rs
- crates/spk-workspace/src/builder.rs
For the use case of `spk info --variants <valid spec file>`, this command would fail with an error about a different file if another file exists with a name matching `*.spk.yaml` but loading this other file fails for any reason.
Like #1190 and #1191, this command is expected to succeed and is not intended to interact with any other files other than the one named on the command line.
> Skip invalid template files when loading workspace

- crates/spk-cli/group2/src/cmd_ls.rs
This just adds `-R` as the short form of `--recursive` for `spk ls` to save on the typing.
> Add `-R` for `--recursive` in `spk ls`

- crates/spk-cli/common/src/flags.rs
- crates/spk-schema/src/spec.rs
Not all spk [env] command lines contain a request that requires the use of a workspace, but previously the workspace was loaded unconditionally, meaning that any/all *.spk.yaml files in the working directory would be read in and possibly warned about if they do not contain the "api" entry.
Avoid this unnecessary file IO overhead when workspaces are not needed.
Also reuse the already loaded workspace instead of creating another new one per file in `parse_idents`.
Finally, if loading a workspace and warning about possibly more than one file if missing the "api" entry, include the filename of the offending file in the warning message.
> Lazily load the default workspace as needed

- README.md
The rustup link was pointing to an invalid link, this PR fixes it.
> Fix rustup link

- crates/spfs-cli/cmd-fuse/src/cmd_fuse.rs
- crates/spfs-cli/cmd-winfsp/src/cmd_winfsp.rs
- crates/spfs-cli/main/src/cmd_run.rs
- crates/spfs-cli/main/src/cmd_shell.rs
- docs/spfs/_index.md
- docs/spfs/usage.md
Providing "nothing" as the docs say after `spfs` doesn't work. This clarifies the commands usage across the repo.
Slack conversation:
https://spk-dev.slack.com/archives/C01UU20QHE0/p1747145971551979
> Clarify spfs shell usage across codebase

- crates/spfs-cli/cmd-clean/src/cmd_clean.rs
- crates/spfs/src/clean.rs
- crates/spfs/src/clean_test.rs
- crates/spfs/src/config.rs
- crates/spfs/src/fixtures.rs
- crates/spfs/src/proto/conversions.rs
- crates/spfs/src/server/tag.rs
- crates/spfs/src/storage/fs/tag.rs
- crates/spfs/src/storage/tag.rs
- crates/spfs/src/storage/tag_namespace.rs
- crates/spfs/src/storage/tag_test.rs
- crates/spfs/src/tracking/tag.rs
This slipped through testing, the clean would immediately fail when it encounters a directory named like "test#ns" as it fails to parse the tag spec, reporting that the "org" is invalid.
This error is avoided by allowing "#ns" to be the suffix of an org and then `spfs clean` seems to work as expected, but ignores all the cases where it _shouldn't_ accept an "org" that contains a namespace.
The current tag stream code doesn't really understand tag namespaces or offer a way to choose to walk into them or skip them. It was intended that `spfs clean` would visit all tags in all namespaces, but otherwise other tag operations would only see tags in the configured namespace.
> Fix `spfs clean` failing if a tag namespace exists

- crates/spk-build/src/build/binary.rs
- crates/spk-cli/cmd-test/src/test/build.rs
- crates/spk-cli/cmd-test/src/test/install.rs
- crates/spk-cli/cmd-test/src/test/sources.rs
- crates/spk-cli/common/src/flags.rs
- crates/spk-exec/src/exec_test.rs
- crates/spk-solve/src/io.rs
- crates/spk-solve/src/lib.rs
- crates/spk-solve/src/solvers/mod.rs
- crates/spk-solve/src/solvers/solver_test.rs
- crates/spk-solve/src/solvers/step/mod.rs
- crates/spk-solve/src/solvers/step/solver.rs
Move `Solver` into a nested module and rename it publicly as `StepSolver` in order to make way for other solver implementations and for the name `Solver` to become available for repurposing it later.
The name `StepSolver` was inspired by how the solver makes progress by calling the `step_state` function.
The `solver_test` module has been separated from the `solver` module since this is destined to become a module of tests that are generic over the solver implementation.
> Restructure spk-solve for multiple solvers

- crates/spfs-cli/cmd-render/src/cmd_render.rs
- crates/spfs/src/resolve.rs
- crates/spfs/src/storage/fs/mod.rs
- crates/spfs/src/storage/fs/renderer.rs
- crates/spfs/src/storage/fs/renderer_unix.rs
This change was prompted by wanting to refactor the code to work towards
having different trait bounds for the functions that need a repository
that supports renders (e.g., rendering into a repository) versus
functions that render into a plain directory.
Rework `RenderType` so the method that renders into a hardlink doesn't
need to worry about getting a `RenderType::Copy` value.
> Refactor rendering logic into separate methods

- cspell.json
- docs-packages/README.md
- docs-packages/gcc-4.spk.yaml
- docs-packages/gcc-6.spk.yaml
- docs-packages/maya2019.spk.yaml
- docs-packages/maya2020.spk.yaml
- docs-packages/my-plugin.spk.yaml
- docs-packages/my-tool.spk.yaml
- docs-packages/qt.spk.yaml
- docs/use/solver.md
- website/layouts/shortcodes/tab.html
- website/layouts/shortcodes/tabs.html
A number of the examples are not really applicable to Resolvo.
Some recipes were added to be able to recreate the output from the existing examples (though the existing output is a little out of date).
The tabs and tab shortcodes were not rendering code blocks as theme documentation suggests it will, so it has been modified to wrap the "content" in a code block. That required removing the triple backticks from the markdown file. Perhaps this can be improved?
> Add Resolvo examples to the Solver Usage documentation

- crates/spfs/src/config_test.rs
thread 'graph::layer::layer_test::test_layer_encoding_annotation_only::write_encoding_format_1_EncodingFormat__Legacy::write_digest_strategy_1_DigestStrategy__Legacy' panicked at crates/spfs/src/graph/./layer_test.rs:44:13:
Encode should fail if encoding format is legacy
Add `serial_test` to another test that modifies the spfs config so it doesn't run concurrently.
This test failure is only reproducible by chance, so it isn't certain that this change (alone) fixes it, but I wasn't able to get the failure to happen again after making this change.
> Fix spurious encode test failure

- crates/spk-schema/crates/ident/src/request.rs
- crates/spk-solve/src/solvers/resolvo/spk_provider.rs
- crates/spk-solve/src/solvers/solver_test.rs
The original solver allows that if a prerelease version of a package is requested then any other install.requirement for that package implicitly allows prereleases too.
There wasn't an existing test to verify this behavior, and resolvo wasn't allowing this.
> Fix resolvo not allowing prereleases

- Cargo.lock
- Cargo.toml
- crates/spk-schema/crates/foundation/src/ident_ops/parsing/mod.rs
- crates/spk-storage/Cargo.toml
- crates/spk-storage/src/lib.rs
- crates/spk-storage/src/walker.rs
- crates/spk-storage/src/walker_test.rs
- cspell.json
This adds  `RepoWalker`, `RepoWalkerBuilder` and supporting objects to the `spk-storage` api crate for spk commands to use.  The aim is to extract the common spk object traversals that commands like `ls`, `search`, `du`, and the new `stats` do, and turn the repeated code into reusable api.
The `RepoWalker` provides a stream of spk objects from a given list of repos, in their hierarchy order: packages, versions, builds, components, and files.
The `RepoWalkerBuilder` allows the caller to configure and create a RepoWalker. Some of the configuration options are taken from the existing spk command use cases, some are more general.
This PR does not include updates to spk command to use a RepoWalker because I'm trying to break up a the changes in more managable PRs. Some of the methods might …
> Add repository walker for spk

- crates/spk-schema/crates/foundation/src/version/mod.rs
- crates/spk-schema/crates/foundation/src/version_range/mod.rs
- crates/spk-schema/crates/tera/src/filter_parse_version.rs
- crates/spk-schema/src/version_range_test.rs
- crates/spk-solve/crates/package-iterator/src/build_key.rs
- crates/spk-solve/crates/package-iterator/src/build_key_test.rs
- crates/spk-storage/src/storage/spfs.rs
This was (presumably) an unintended consequence of using "less_than" to transform "~1.2.3" into "<1.3.0" and pre-releases being considered less than their non-pre-release counterparts.
As documented, "~1.2.3" should only allow the patch version to change.
To fix this, the "plus_epsilon" concept was expanded to cover both "plus" and "minus" cases. It mirrors how "plus_epsilon" was created to solve a similar problem with using "greater_or_equal_to" for situations than really need "greater_than" instead.
> Fix "~1.2.3" matching "1.3.0-pre.1"

- crates/spk-cli/group2/src/cmd_ls.rs
This adds `--build-options-display/-b ...` command line flag to `spk ls` to control how build options are displayed when `-v` is set.  It provides an enum for having different ways of displaying build options, and implements two to start with: all, and diff.
This might be starting point for satifying:  https://github.com/spkenv/spk/issues/590
The default is `-b all`, which keeps the build options display the same as if was before, e.g.:
```
> spk ls python/3.9.7 -v -b all
[origin] python/3.9.7/MMHZ5SV2 {abi=cp39, arch=x86_64, bzip2=~1.0.6, centos=7, debug=off, distro=centos, gcc=~6.3.1, os=linux, pymalloc=on, stdfs=~1.0}
[origin] python/3.9.7/VOWI3RWU {abi=cp39, arch=x86_64, bzip2=~1.0.6, centos=, debug=off, distro=rocky, gcc=~11.4.1, os=linux, pymalloc=on, rocky=9.3, stdfs=~1.1}
[origin] …
```
> Add `--build-options-display/-b ...` option to `spk ls`

- crates/spfs-cli/main/src/cmd_push.rs
This fixes a bug that stopped spfs push from defaulting to the origin repo for the destintion. It restores the default `remote` repo argument value to `origin`. This bug came in when spfs commands had their repos arguments updated to allow wrapping repos with proxy repos.
> Bugfix: spfs push stopped defaulting to origin for remote repo

- Cargo.lock
- Cargo.toml
- crates/spk-cli/common/Cargo.toml
- crates/spk-storage/Cargo.toml
Dependabot suggested in #1248 to patch a security issue but as described in https://github.com/tokio-rs/tracing/issues/3369 there seems to be no way to opt back in to allowing escape sequences and now many of our log messages have visible escape sequences in them.
> Lock tracing-subscriber to get text colors back

- crates/spfs/src/sync.rs
- crates/spfs/src/sync_test.rs
This fixes a bug that was preventing annotation blob value's from syncing. The issue was the processing insert checks were happening at all the levels,  including the top level of annotation syncing method. And that made the lower levels (sync_object, sync_blob) think the annotation's blob digest has been already sync'd.
This also adds a sync test for an annotation blob in a layer.
> Bugfix: annotation blob value syncing

- .github/workflows/coverage.yml
- crates/spfs-cli/cmd-render/src/cmd_render.rs
- crates/spfs/src/config.rs
- crates/spfs/src/resolve.rs
- crates/spfs/src/storage/error.rs
- crates/spfs/src/storage/fallback/repository.rs
- crates/spfs/src/storage/fallback/repository_test.rs
- crates/spfs/src/storage/proxy/mod.rs
- crates/spfs/src/storage/proxy/repository.rs
- crates/spk-cli/cmd-render/src/cmd_render.rs
- crates/spk-launcher/src/main.rs
Missed adding this back when FallbackProxy was implemented.
Also update the FallbackProxy type to have the same tag reading features that the Proxy type has. They now behave nearly the same but the FallbackProxy still propagates payloads into the primary repo.
> Add missing support for "fallback" repository schema

- codecov.yml
- crates/spfs-vfs/src/fuse.rs
- crates/spfs/src/error.rs
When opening a payload, also continue checking the next repositories if the error was ObjectMissingPayload. Otherwise some file I/O that could succeed will fail if the local repository is missing payloads.
> Fuse missing payload handling
